apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: middlemanager
  name: middlemanager
spec:
  ports:
    - name: "8091"
      port: 8091
      targetPort: 8091
    - name: "8100"
      port: 8100
      targetPort: 8100
    - name: "8101"
      port: 8101
      targetPort: 8101
    - name: "8102"
      port: 8102
      targetPort: 8102
    - name: "8103"
      port: 8103
      targetPort: 8103
    - name: "8104"
      port: 8104
      targetPort: 8104
    - name: "8105"
      port: 8105
      targetPort: 8105
  selector:
    io.kompose.service: middlemanager
status:
  loadBalancer: {}
