apiVersion: v1
kind: Service
metadata:
  name: love-and-marriage-service
spec:
  selector:
    app: love-and-marriage
  ports:
  - protocol: "TCP"
    port: 8001
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: love-and-marriage
spec:
  selector:
    matchLabels:
      app: love-and-marriage
  replicas: 4
  template:
    metadata:
      labels:
        app: love-and-marriage
    spec:
      containers:
      - name: love-and-marriage
        image: love_and_marriag:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
