apiVersion: v1
kind: Service
metadata:
  name: scraper
spec:
  selector:
    app: scraper
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
spec:
  selector:
    matchLabels:
      app: scraper
  replicas: 1
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: scraper:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: APP_PORT
          value: "8000"
        livenessProbe:
          httpGet:
            path: /health_check
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /health_check
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
