CREATE TABLE country (
    id_cntry     SMALLSERIAL CONSTRAINT cntry_first_key PRIMARY KEY,
    cntry_name   varchar(40) NOT NULL
);

INSERT INTO country (id_cntry, cntry_name) VALUES ('0', 'All');
INSERT INTO country (cntry_name) VALUES
('Afganistan'),
('Albania'),
('Algieria'),
('Andora'),
('Angola'),
('Antigua i Barbuda'),
('Arabia Saudyjska'),
('Argentyna'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbejdżan'),
('Bahamy'),
('Bahrajn'),
('Bangladesz'),
('Barbados'),
('Belgia'),
('Belize'),
('Benin'),
('Bhutan'),
('Białoruś'),
('Boliwia'),
('Bośnia i Hercegowina'),
('Botswana'),
('Brazylia'),
('Brunei'),
('Bułgaria'),
('Burkina Faso'),
('Burundi'),
('Chile'),
('Chiny'),
('Chorwacja'),
('Cypr'),
('Czad'),
('Czarnogóra'),
('Czechy'),
('Dania'),
('Demokratyczna Republika Konga'),
('Dominika'),
('Dominikana'),
('Dżibuti'),
('Egipt'),
('Ekwador'),
('Erytrea'),
('Estonia'),
('Eswatini'),
('Etiopia'),
('Fidżi'),
('Filipiny'),
('Finlandia'),
('Francja'),
('Gabon'),
('Gambia'),
('Ghana'),
('Grecja'),
('Grenada'),
('Gruzja'),
('Gujana'),
('Gwatemala'),
('Gwinea'),
('Gwinea Bissau'),
('Gwinea Równikowa'),
('Haiti'),
('Hiszpania'),
('Holandia'),
('Honduras'),
('Indie'),
('Indonezja'),
('Irak'),
('Iran'),
('Irlandia'),
('Islandia'),
('Izrael'),
('Jamajka'),
('Japonia'),
('Jemen'),
('Jordania'),
('Kambodża'),
('Kamerun'),
('Kanada'),
('Katar'),
('Kazachstan'),
('Kenia'),
('Kirgistan'),
('Kiribati'),
('Kolumbia'),
('Komory'),
('Kongo'),
('Korea Południowa'),
('Korea Północna'),
('Kostaryka'),
('Kuba'),
('Kuwejt'),
('Laos'),
('Lesotho'),
('Liban'),
('Liberia'),
('Libia'),
('Liechtenstein'),
('Litwa'),
('Luksemburg'),
('Łotwa'),
('Macedonia Północna'),
('Madagaskar'),
('Malawi'),
('Malediwy'),
('Malezja'),
('Mali'),
('Malta'),
('Maroko'),
('Mauretania'),
('Mauritius'),
('Meksyk'),
('Mikronezja'),
('Mjanma'),
('Mołdawia'),
('Monako'),
('Mongolia'),
('Mozambik'),
('Namibia'),
('Nauru'),
('Nepal'),
('Niemcy'),
('Niger'),
('Nigeria'),
('Nikaragua'),
('Norwegia'),
('Nowa Zelandia'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua-Nowa Gwinea'),
('Paragwaj'),
('Peru'),
('Polska'),
('Południowa Afryka'),
('Portugalia'),
('Republika Środkowoafrykańska'),
('Republika Zielonego Przylądka'),
('Rosja'),
('Rumunia'),
('Rwanda'),
('Saint Kitts i Nevis'),
('Saint Lucia'),
('Saint Vincent i Grenadyny'),
('Salwador'),
('Samoa'),
('San Marino'),
('Senegal'),
('Serbia'),
('Seszele'),
('Sierra Leone'),
('Singapur'),
('Słowacja'),
('Słowenia'),
('Somalia'),
('Sri Lanka'),
('Stany Zjednoczone'),
('Sudan'),
('Sudan Południowy'),
('Surinam'),
('Syria'),
('Szwajcaria'),
('Szwecja'),
('Tadżykistan'),
('Tajlandia'),
('Tanzania'),
('Timor Wschodni'),
('Togo'),
('Tonga'),
('Trynidad i Tobago'),
('Tunezja'),
('Turcja'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraina'),
('Urugwaj'),
('Uzbekistan'),
('Vanuatu'),
('Watykan'),
('Wenezuela'),
('Węgry'),
('Wielka Brytania'),
('Wietnam'),
('Włochy'),
('Wybrzeże Kości Słoniowej'),
('Wyspy Marshalla'),
('Wyspy Salomona'),
('Wyspy Świętego Tomasza i Książęca'),
('Zambia'),
('Zimbabwe'),
('Zjednoczone Emiraty Arabskie');

CREATE TABLE province (
    id_province   SERIAL CONSTRAINT province_first_key PRIMARY KEY,
    province_name varchar(40) NOT NULL,
    id_cntry      SMALLINT NOT NULL,
    CONSTRAINT fk_cntry FOREIGN KEY(id_cntry) REFERENCES country(id_cntry)
);

INSERT INTO province (province_name, id_cntry) VALUES
('dolnośląskie', '136'),
('kujawsko-pomorskie', '136'),
('lubelskie', '136'),
('lubuskie', '136'),
('łódzkie', '136'),
('małopolskie', '136'),
('mazowieckie', '136'),
('opolskie', '136'),
('podkarpackie', '136'),
('podlaskie', '136'),
('pomorskie', '136'),
('śląskie', '136'),
('świętokrzyskie', '136'),
('warmińsko-mazurskie', '136'),
('wielkopolskie', '136'),
('zachodniopomorskie', '136');
INSERT INTO province (province_name, id_cntry) VALUES
('All', '136');

CREATE TABLE district (
    id_district   SERIAL CONSTRAINT district_first_key PRIMARY KEY,
    district_name varchar(40) NOT NULL,
    id_province   INT NOT NULL,
    CONSTRAINT fk_province FOREIGN KEY(id_province) REFERENCES province(id_province)
);
INSERT INTO district (district_name, id_province) VALUES
('bolesławiecki', '1'),
('dzierżoniowski', '1'),
('głogowski', '1'),
('górowski', '1'),
('jaworski', '1'),
('jeleniogórski', '1'),
('kamiennogórski', '1'),
('kłodzki', '1'),
('legnicki', '1'),
('lubański', '1'),
('lubiński', '1'),
('lwówecki', '1'),
('milicki', '1'),
('oleśnicki', '1'),
('oławski', '1'),
('polkowicki', '1'),
('strzeliński', '1'),
('średzki', '1'),
('świdnicki', '1'),
('trzebnicki', '1'),
('wałbrzyski', '1'),
('wołowski', '1'),
('wrocławski', '1'),
('ząbkowicki', '1'),
('zgorzelecki', '1'),
('złotoryjski', '1'),
('Jelenia Góra', '1'),
('Legnica', '1'),
('Wrocław', '1'),
('Wałbrzych', '1'),
('aleksandrowski', '2'),
('brodnicki', '2'),
('bydgoski', '2'),
('chełmiński', '2'),
('golubsko-dobrzyński', '2'),
('grudziądzki', '2'),
('inowrocławski', '2'),
('lipnowski', '2'),
('mogileński', '2'),
('nakielski', '2'),
('radziejowski', '2'),
('rypiński', '2'),
('sępoleński', '2'),
('świecki', '2'),
('toruński', '2'),
('tucholski', '2'),
('wąbrzeski', '2'),
('włocławski', '2'),
('żniński', '2'),
('Bydgoszcz', '2'),
('Grudziądz', '2'),
('Toruń', '2'),
('Włocławek', '2'),
('bialski', '3'),
('biłgorajski', '3'),
('chełmski', '3'),
('hrubieszowski', '3'),
('janowski', '3'),
('krasnostawski', '3'),
('kraśnicki', '3'),
('lubartowski', '3'),
('lubelski', '3'),
('łęczyński', '3'),
('łukowski', '3'),
('opolski', '3'),
('parczewski', '3'),
('puławski', '3'),
('radzyński', '3'),
('rycki', '3'),
('świdnicki', '3'),
('tomaszowski', '3'),
('włodawski', '3'),
('zamojski', '3'),
('Biała Podlaska', '3'),
('Chełm', '3'),
('Lublin', '3'),
('Zamość', '3'),
('gorzowski', '4'),
('krośnieński', '4'),
('międzyrzecki', '4'),
('nowosolski', '4'),
('słubicki', '4'),
('strzelecko-drezdenecki', '4'),
('sulęciński', '4'),
('świebodziński', '4'),
('zielonogórski', '4'),
('żagański', '4'),
('żarski', '4'),
('wschowski', '4'),
('Gorzów Wielkopolski', '4'),
('Zielona Góra', '4'),
('bełchatowski', '5'),
('kutnowski', '5'),
('łaski', '5'),
('łęczycki', '5'),
('łowicki', '5'),
('łódzki wschodni', '5'),
('opoczyński', '5'),
('pabianicki', '5'),
('pajęczański', '5'),
('piotrkowski', '5'),
('poddębicki', '5'),
('radomszczański', '5'),
('rawski', '5'),
('sieradzki', '5'),
('skierniewicki', '5'),
('tomaszowski', '5'),
('wieluński', '5'),
('wieruszowski', '5'),
('zduńskowolski', '5'),
('zgierski', '5'),
('brzeziński', '5'),
('Łódź', '5'),
('Piotrków Trybunalski', '5'),
('Skierniewice', '5'),
('bocheński', '6'),
('brzeski', '6'),
('chrzanowski', '6'),
('dąbrowski', '6'),
('gorlicki', '6'),
('krakowski', '6'),
('limanowski', '6'),
('miechowski', '6'),
('myślenicki', '6'),
('nowosądecki', '6'),
('nowotarski', '6'),
('olkuski', '6'),
('oświęcimski', '6'),
('proszowicki', '6'),
('suski', '6'),
('tarnowski', '6'),
('tatrzański', '6'),
('wadowicki', '6'),
('wielicki', '6'),
('Kraków', '6'),
('Nowy Sącz', '6'),
('Tarnów', '6'),
('białobrzeski', '7'),
('ciechanowski', '7'),
('garwoliński', '7'),
('gostyniński', '7'),
('grodziski', '7'),
('grójecki', '7'),
('kozienicki', '7'),
('legionowski', '7'),
('lipski', '7'),
('łosicki', '7'),
('makowski', '7'),
('miński', '7'),
('mławski', '7'),
('nowodworski', '7'),
('ostrołęcki', '7'),
('ostrowski', '7'),
('otwocki', '7'),
('piaseczyński', '7'),
('płocki', '7'),
('płoński', '7'),
('pruszkowski', '7'),
('przasnyski', '7'),
('przysuski', '7'),
('pułtuski', '7'),
('radomski', '7'),
('siedlecki', '7'),
('sierpecki', '7'),
('sochaczewski', '7'),
('sokołowski', '7'),
('szydłowiecki', '7'),
('warszawski zachodni', '7'),
('węgrowski', '7'),
('wołomiński', '7'),
('wyszkowski', '7'),
('zwoleński', '7'),
('żuromiński', '7'),
('żyrardowski', '7'),
('Ostrołęka', '7'),
('Płock', '7'),
('Radom', '7'),
('Siedlce', '7'),
('Warszawa', '7'),
('brzeski', '8'),
('głubczycki', '8'),
('kędzierzyńsko-kozielski', '8'),
('kluczborski', '8'),
('krapkowicki', '8'),
('namysłowski', '8'),
('nyski', '8'),
('oleski', '8'),
('opolski', '8'),
('prudnicki', '8'),
('strzelecki', '8'),
('Opole', '8'),
('bieszczadzki', '9'),
('brzozowski', '9'),
('dębicki', '9'),
('jarosławski', '9'),
('jasielski', '9'),
('kolbuszowski', '9'),
('krośnieński', '9'),
('leżajski', '9'),
('lubaczowski', '9'),
('łańcucki', '9'),
('mielecki', '9'),
('niżański', '9'),
('przemyski', '9'),
('przeworski', '9'),
('ropczycko-sędziszowski', '9'),
('rzeszowski', '9'),
('sanocki', '9'),
('stalowowolski', '9'),
('strzyżowski', '9'),
('tarnobrzeski', '9'),
('leski', '9'),
('Krosno', '9'),
('Przemyśl', '9'),
('Rzeszów', '9'),
('Tarnobrzeg', '9'),
('augustowski', '10'),
('białostocki', '10'),
('bielski', '10'),
('grajewski', '10'),
('hajnowski', '10'),
('kolneński', '10'),
('łomżyński', '10'),
('moniecki', '10'),
('sejneński', '10'),
('siemiatycki', '10'),
('sokólski', '10'),
('suwalski', '10'),
('wysokomazowiecki', '10'),
('zambrowski', '10'),
('Białystok', '10'),
('Łomża', '10'),
('Suwałki', '10'),
('bytowski', '11'),
('chojnicki', '11'),
('człuchowski', '11'),
('gdański', '11'),
('kartuski', '11'),
('kościerski', '11'),
('kwidzyński', '11'),
('lęborski', '11'),
('malborski', '11'),
('nowodworski', '11'),
('pucki', '11'),
('słupski', '11'),
('starogardzki', '11'),
('tczewski', '11'),
('wejherowski', '11'),
('sztumski', '11'),
('Gdańsk', '11'),
('Gdynia', '11'),
('Słupsk', '11'),
('Sopot', '11'),
('będziński', '12'),
('bielski', '12'),
('cieszyński', '12'),
('częstochowski', '12'),
('gliwicki', '12'),
('kłobucki', '12'),
('lubliniecki', '12'),
('mikołowski', '12'),
('myszkowski', '12'),
('pszczyński', '12'),
('raciborski', '12'),
('rybnicki', '12'),
('tarnogórski', '12'),
('bieruńsko-lędziński', '12'),
('wodzisławski', '12'),
('zawierciański', '12'),
('żywiecki', '12'),
('Bielsko-Biała', '12'),
('Bytom', '12'),
('Chorzów', '12'),
('Częstochowa', '12'),
('Dąbrowa Górnicza', '12'),
('Gliwice', '12'),
('Jastrzębie-Zdrój', '12'),
('Jaworzno', '12'),
('Katowice', '12'),
('Mysłowice', '12'),
('Piekary Śląskie', '12'),
('Ruda Śląska', '12'),
('Rybnik', '12'),
('Siemianowice Śląskie', '12'),
('Sosnowiec', '12'),
('Świętochłowice', '12'),
('Tychy', '12'),
('Zabrze', '12'),
('Żory', '12'),
('buski', '13'),
('jędrzejowski', '13'),
('kazimierski', '13'),
('kielecki', '13'),
('konecki', '13'),
('opatowski', '13'),
('ostrowiecki', '13'),
('pińczowski', '13'),
('sandomierski', '13'),
('skarżyski', '13'),
('starachowicki', '13'),
('staszowski', '13'),
('włoszczowski', '13'),
('Kielce', '13'),
('bartoszycki', '14'),
('braniewski', '14'),
('działdowski', '14'),
('elbląski', '14'),
('ełcki', '14'),
('giżycki', '14'),
('iławski', '14'),
('kętrzyński', '14'),
('lidzbarski', '14'),
('mrągowski', '14'),
('nidzicki', '14'),
('nowomiejski', '14'),
('olecki', '14'),
('olsztyński', '14'),
('ostródzki', '14'),
('piski', '14'),
('szczycieński', '14'),
('gołdapski', '14'),
('węgorzewski', '14'),
('Elbląg', '14'),
('Olsztyn', '14'),
('chodzieski', '15'),
('czarnkowsko-trzcianecki', '15'),
('gnieźnieński', '15'),
('gostyński', '15'),
('grodziski', '15'),
('jarociński', '15'),
('kaliski', '15'),
('kępiński', '15'),
('kolski', '15'),
('koniński', '15'),
('kościański', '15'),
('krotoszyński', '15'),
('leszczyński', '15'),
('międzychodzki', '15'),
('nowotomyski', '15'),
('obornicki', '15'),
('ostrowski', '15'),
('ostrzeszowski', '15'),
('pilski', '15'),
('pleszewski', '15'),
('poznański', '15'),
('rawicki', '15'),
('słupecki', '15'),
('szamotulski', '15'),
('średzki', '15'),
('śremski', '15'),
('turecki', '15'),
('wągrowiecki', '15'),
('wolsztyński', '15'),
('wrzesiński', '15'),
('złotowski', '15'),
('Kalisz', '15'),
('Konin', '15'),
('Leszno', '15'),
('Poznań', '15'),
('białogardzki', '16'),
('choszczeński', '16'),
('drawski', '16'),
('goleniowski', '16'),
('gryficki', '16'),
('gryfiński', '16'),
('kamieński', '16'),
('kołobrzeski', '16'),
('koszaliński', '16'),
('myśliborski', '16'),
('policki', '16'),
('pyrzycki', '16'),
('sławieński', '16'),
('stargardzki', '16'),
('szczecinecki', '16'),
('świdwiński', '16'),
('wałecki', '16'),
('łobeski', '16'),
('Koszalin', '16'),
('Szczecin', '16'),
('Świnoujście', '16');
INSERT INTO district (district_name, id_province) VALUES
('All', '1'),
('All', '2'),
('All', '3'),
('All', '4'),
('All', '5'),
('All', '6'),
('All', '7'),
('All', '8'),
('All', '9'),
('All', '10'),
('All', '11'),
('All', '12'),
('All', '13'),
('All', '14'),
('All', '15'),
('All', '16');

CREATE TABLE cases
(
    id_cases    SERIAL
        CONSTRAINT cases_fisrt_key PRIMARY KEY,
    day         date     NOT NULL,
    id_cntry    SMALLINT NOT NULL,
    id_province INT,
    id_district INT,
    cases       SMALLINT NOT NULL,
    deaths      SMALLINT,
    recovered   SMALLINT,
    CONSTRAINT fk_cntry FOREIGN KEY (id_cntry) REFERENCES country (id_cntry),
    CONSTRAINT fk_province FOREIGN KEY (id_province) REFERENCES province (id_province),
    CONSTRAINT fk_district FOREIGN KEY (id_district) REFERENCES district (id_district)
);

CREATE TABLE events
(
    id_event SERIAL
        CONSTRAINT event_fisrt_key PRIMARY KEY,
    day      date     NOT NULL,
    event    VARCHAR NOT NULL
);

INSERT INTO events (day, event) VALUES
('2019-11-17', '(probably) first case of COVID-19, China');

-- co z testami błędnie wykonanymi? other? total? jak to sie ma do cases
-- CREATE TABLE tests
-- (
--     id_tests    SERIAL
--         CONSTRAINT tests_fisrt_key PRIMARY KEY,
--     day         date     NOT NULL,
--     id_cntry    SMALLINT NOT NULL,
--     id_province INT,
--     id_district INT,
--     positive_tests     SMALLINT,
--     negative_tests     SMALLINT,
--     CONSTRAINT fk_cntry FOREIGN KEY (id_cntry) REFERENCES country (id_cntry),
--     CONSTRAINT fk_province FOREIGN KEY (id_province) REFERENCES province (id_province),
--     CONSTRAINT fk_district FOREIGN KEY (id_district) REFERENCES district (id_district)
-- )

-- hospitalizacje, kwarantanna, nadzór
-- CREATE TABLE ?????
-- (
--     id_?????    SERIAL
--         CONSTRAINT ?????_fisrt_key PRIMARY KEY,
--     day         date     NOT NULL,
--     id_cntry    SMALLINT NOT NULL,
--     id_province INT,
--     id_district INT,
--     hospitalisation SMALLINT,
--     quarantine      SMALLINT,
--     supervision     SMALLINT,
--     CONSTRAINT fk_cntry FOREIGN KEY (id_cntry) REFERENCES country (id_cntry),
--     CONSTRAINT fk_province FOREIGN KEY (id_province) REFERENCES province (id_province),
--     CONSTRAINT fk_district FOREIGN KEY (id_district) REFERENCES district (id_district)
-- )

-- czwarte i kolejne dawki?
-- CREATE TABLE vaccination
-- (
--     id_vaccine    SERIAL
--         CONSTRAINT vaccine_fisrt_key PRIMARY KEY,
--     day         date     NOT NULL,
--     id_cntry    SMALLINT NOT NULL,
--     id_province INT,
--     id_district INT,
--     vaccine_1st_dose SMALLINT,
--     vaccine_2nd_dose SMALLINT,
--     vaccine_3rd_dose SMALLINT,
--     CONSTRAINT fk_cntry FOREIGN KEY (id_cntry) REFERENCES country (id_cntry),
--     CONSTRAINT fk_province FOREIGN KEY (id_province) REFERENCES province (id_province),
--     CONSTRAINT fk_district FOREIGN KEY (id_district) REFERENCES district (id_district)
-- )