CREATE TABLE country (
    id_cntry     SMALLSERIAL CONSTRAINT cntry_first_key PRIMARY KEY,
    cntry_name   varchar(40) NOT NULL
);

INSERT INTO country (id_cntry, cntry_name) VALUES ('0', 'All');
INSERT INTO country (cntry_name) VALUES
('Afganistan'),
('Albania'),
('Algieria'),
('Andora'),
('Angola'),
('Antigua i Barbuda'),
('Arabia Saudyjska'),
('Argentyna'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbejdżan'),
('Bahamy'),
('Bahrajn'),
('Bangladesz'),
('Barbados'),
('Belgia'),
('Belize'),
('Benin'),
('Bhutan'),
('Białoruś'),
('Boliwia'),
('Bośnia i Hercegowina'),
('Botswana'),
('Brazylia'),
('Brunei'),
('Bułgaria'),
('Burkina Faso'),
('Burundi'),
('Chile'),
('Chiny'),
('Chorwacja'),
('Cypr'),
('Czad'),
('Czarnogóra'),
('Czechy'),
('Dania'),
('Demokratyczna Republika Konga'),
('Dominika'),
('Dominikana'),
('Dżibuti'),
('Egipt'),
('Ekwador'),
('Erytrea'),
('Estonia'),
('Eswatini'),
('Etiopia'),
('Fidżi'),
('Filipiny'),
('Finlandia'),
('Francja'),
('Gabon'),
('Gambia'),
('Ghana'),
('Grecja'),
('Grenada'),
('Gruzja'),
('Gujana'),
('Gwatemala'),
('Gwinea'),
('Gwinea Bissau'),
('Gwinea Równikowa'),
('Haiti'),
('Hiszpania'),
('Holandia'),
('Honduras'),
('Indie'),
('Indonezja'),
('Irak'),
('Iran'),
('Irlandia'),
('Islandia'),
('Izrael'),
('Jamajka'),
('Japonia'),
('Jemen'),
('Jordania'),
('Kambodża'),
('Kamerun'),
('Kanada'),
('Katar'),
('Kazachstan'),
('Kenia'),
('Kirgistan'),
('Kiribati'),
('Kolumbia'),
('Komory'),
('Kongo'),
('Korea Południowa'),
('Korea Północna'),
('Kostaryka'),
('Kuba'),
('Kuwejt'),
('Laos'),
('Lesotho'),
('Liban'),
('Liberia'),
('Libia'),
('Liechtenstein'),
('Litwa'),
('Luksemburg'),
('Łotwa'),
('Macedonia Północna'),
('Madagaskar'),
('Malawi'),
('Malediwy'),
('Malezja'),
('Mali'),
('Malta'),
('Maroko'),
('Mauretania'),
('Mauritius'),
('Meksyk'),
('Mikronezja'),
('Mjanma'),
('Mołdawia'),
('Monako'),
('Mongolia'),
('Mozambik'),
('Namibia'),
('Nauru'),
('Nepal'),
('Niemcy'),
('Niger'),
('Nigeria'),
('Nikaragua'),
('Norwegia'),
('Nowa Zelandia'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua-Nowa Gwinea'),
('Paragwaj'),
('Peru'),
('Polska'),
('Południowa Afryka'),
('Portugalia'),
('Republika Środkowoafrykańska'),
('Republika Zielonego Przylądka'),
('Rosja'),
('Rumunia'),
('Rwanda'),
('Saint Kitts i Nevis'),
('Saint Lucia'),
('Saint Vincent i Grenadyny'),
('Salwador'),
('Samoa'),
('San Marino'),
('Senegal'),
('Serbia'),
('Seszele'),
('Sierra Leone'),
('Singapur'),
('Słowacja'),
('Słowenia'),
('Somalia'),
('Sri Lanka'),
('Stany Zjednoczone'),
('Sudan'),
('Sudan Południowy'),
('Surinam'),
('Syria'),
('Szwajcaria'),
('Szwecja'),
('Tadżykistan'),
('Tajlandia'),
('Tanzania'),
('Timor Wschodni'),
('Togo'),
('Tonga'),
('Trynidad i Tobago'),
('Tunezja'),
('Turcja'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraina'),
('Urugwaj'),
('Uzbekistan'),
('Vanuatu'),
('Watykan'),
('Wenezuela'),
('Węgry'),
('Wielka Brytania'),
('Wietnam'),
('Włochy'),
('Wybrzeże Kości Słoniowej'),
('Wyspy Marshalla'),
('Wyspy Salomona'),
('Wyspy Świętego Tomasza i Książęca'),
('Zambia'),
('Zimbabwe'),
('Zjednoczone Emiraty Arabskie');

CREATE TABLE province (
    id_province   SERIAL CONSTRAINT province_first_key PRIMARY KEY,
    province_name varchar(40) NOT NULL,
    id_cntry      SMALLINT NOT NULL,
    CONSTRAINT fk_cntry FOREIGN KEY(id_cntry) REFERENCES country(id_cntry)
);
INSERT INTO province (id_province, province_name, id_cntry) VALUES (0, 'śląskie', '136');
INSERT INTO province (province_name, id_cntry) VALUES
('opolskie', '136'),
('wielkopolskie', '136'),
('zachodniopomorskie', '136'),
('świętokrzyskie', '136'),
('kujawsko-pomorskie', '136'),
('podlaskie', '136'),
('dolnośląskie', '136'),
('podkarpackie', '136'),
('małopolskie', '136'),
('pomorskie', '136'),
('warmińsko-mazurskie', '136'),
('łódzkie', '136'),
('mazowieckie', '136'),
('lubelskie', '136'),
('lubuskie', '136'),
('All', '136');

CREATE TABLE district (
    id_district   SERIAL CONSTRAINT district_first_key PRIMARY KEY,
    district_name varchar(40) NOT NULL,
    id_province   INT NOT NULL,
    CONSTRAINT fk_province FOREIGN KEY(id_province) REFERENCES province(id_province)
);

INSERT INTO district (id_district, district_name, id_province) VALUES
(0, 'ropczycko-sędziszowski', 8);

INSERT INTO district (district_name, id_province) VALUES
('łosicki', 13),
('piaseczyński', 13),
('radomski', 13),
('sierpecki', 13),
('szydłowiecki', 13),
('węgrowski', 13),
('gostyniński', 13),
('grodziski', 13),
('łukowski', 14),
('tomaszowski', 14),
('Chełm', 14),
('brzeski', 9),
('Kraków', 9),
('zgierski', 12),
('sulęciński', 15),
('łańcucki', 8),
('brzeski', 1),
('ostrzeszowski', 2),
('Radom', 13),
('żyrardowski', 13),
('obornicki', 2),
('leszczyński', 2),
('Siedlce', 13),
('Leszno', 2),
('kolski', 2),
('Łomża', 6),
('rawicki', 2),
('słupecki', 2),
('kościerski', 10),
('włoszczowski', 4),
('stargardzki', 3),
('Wrocław', 7),
('giżycki', 11),
('mrągowski', 11),
('głogowski', 7),
('choszczeński', 3),
('Sosnowiec', 0),
('rybnicki', 0),
('Gliwice', 0),
('Piekary Śląskie', 0),
('Jaworzno', 0),
('inowrocławski', 5),
('brodnicki', 5),
('włocławski', 5),
('mogileński', 5),
('Toruń', 5),
('tucholski', 5),
('raciborski', 0),
('cieszyński', 0),
('krośnieński', 8),
('nyski', 1),
('Jelenia Góra', 7),
('zgorzelecki', 7),
('przasnyski', 13),
('Ostrołęka', 13),
('średzki', 2),
('jarociński', 2),
('Gdynia', 10),
('Świnoujście', 3),
('kamiennogórski', 7),
('pabianicki', 12),
('kolneński', 6),
('Opole', 1),
('ostródzki', 11),
('przemyski', 8),
('Przemyśl', 8),
('warszawski zachodni', 13),
('włodawski', 14),
('Lublin', 14),
('bocheński', 9),
('Tarnów', 9),
('wschowski', 15),
('gorzowski', 15),
('międzyrzecki', 15),
('słubicki', 15),
('nowotomyski', 2),
('wągrowiecki', 2),
('bielski', 6),
('suwalski', 6),
('słupski', 10),
('ostrowiecki', 4),
('skarżyski', 4),
('kartuski', 10),
('częstochowski', 0),
('pyrzycki', 3),
('Siemianowice Śląskie', 0),
('Elbląg', 11),
('gryfiński', 3),
('Bytom', 0),
('złotoryjski', 7),
('wrocławski', 7),
('milicki', 7),
('lubiński', 7),
('lipnowski', 5),
('żniński', 5),
('radziejowski', 5),
('nakielski', 5),
('bartoszycki', 11),
('żywiecki', 0),
('sokólski', 6),
('jasielski', 8),
('głubczycki', 1),
('nowosądecki', 9),
('Zielona Góra', 15),
('Skierniewice', 12),
('żagański', 15),
('Gdańsk', 10),
('lęborski', 10),
('Łódź', 12),
('piotrkowski', 12),
('ostrowski', 13),
('starogardzki', 10),
('Poznań', 2),
('Konin', 2),
('stalowowolski', 8),
('Tarnobrzeg', 8),
('płoński', 13),
('mławski', 13),
('siedlecki', 13),
('garwoliński', 13),
('lipski', 13),
('hrubieszowski', 14),
('kraśnicki', 14),
('łęczyński', 14),
('opolski', 14),
('rycki', 14),
('Zamość', 14),
('dąbrowski', 9),
('krakowski', 9),
('wieruszowski', 12),
('żarski', 15),
('krośnieński', 15),
('dębicki', 8),
('namysłowski', 1),
('czarnkowsko-trzcianecki', 2),
('Płock', 13),
('grajewski', 6),
('starachowicki', 4),
('konecki', 4),
('elbląski', 11),
('nidzicki', 11),
('nowomiejski', 11),
('Ruda Śląska', 0),
('białogardzki', 3),
('tarnogórski', 0),
('zawierciański', 0),
('Chorzów', 0),
('Katowice', 0),
('bolesławiecki', 7),
('Wałbrzych', 7),
('sępoleński', 5),
('Włocławek', 5),
('hajnowski', 6),
('chrzanowski', 9),
('wejherowski', 10),
('Szczecin', 3),
('pucki', 10),
('rawski', 12),
('łowicki', 12),
('skierniewicki', 12),
('iławski', 11),
('niżański', 8),
('tarnobrzeski', 8),
('nowodworski', 13),
('pruszkowski', 13),
('przysuski', 13),
('białobrzeski', 13),
('wyszkowski', 13),
('biłgorajski', 14),
('chełmski', 14),
('parczewski', 14),
('świdnicki', 14),
('kutnowski', 12),
('łódzki wschodni', 12),
('kolbuszowski', 8),
('oleski', 1),
('strzelecki', 1),
('złotowski', 2),
('Suwałki', 6),
('kościański', 2),
('grodziski', 2),
('szamotulski', 2),
('Kielce', 4),
('staszowski', 4),
('ełcki', 11),
('dzierżoniowski', 7),
('tczewski', 10),
('kołobrzeski', 3),
('Koszalin', 3),
('kłobucki', 0),
('gliwicki', 0),
('lubliniecki', 0),
('Bielsko-Biała', 0),
('Legnica', 7),
('grudziądzki', 5),
('wołowski', 7),
('toruński', 5),
('chełmiński', 5),
('wodzisławski', 0),
('leski', 8),
('bieszczadzki', 8),
('prudnicki', 1),
('ząbkowicki', 7),
('makowski', 13),
('pszczyński', 0),
('gołdapski', 11),
('Sopot', 10),
('rzeszowski', 8),
('jeleniogórski', 7),
('świdnicki', 7),
('opoczyński', 12),
('człuchowski', 10),
('ostrowski', 2),
('Kalisz', 2),
('strzyżowski', 8),
('miński', 13),
('zwoleński', 13),
('żuromiński', 13),
('lubelski', 14),
('proszowicki', 9),
('wielicki', 9),
('sieradzki', 12),
('brzeziński', 12),
('strzelecko-drezdenecki', 15),
('świebodziński', 15),
('leżajski', 8),
('lubaczowski', 8),
('chodzieski', 2),
('międzychodzki', 2),
('kluczborski', 1),
('jędrzejowski', 4),
('gostyński', 2),
('kazimierski', 4),
('kaliski', 2),
('siemiatycki', 6),
('gdański', 10),
('szczycieński', 11),
('łobeski', 3),
('gryficki', 3),
('myszkowski', 0),
('oleśnicki', 7),
('strzeliński', 7),
('wąbrzeski', 5),
('kętrzyński', 11),
('białostocki', 6),
('augustowski', 6),
('wałbrzyski', 7),
('kłodzki', 7),
('Tychy', 0),
('Rybnik', 0),
('sokołowski', 13),
('grójecki', 13),
('lubartowski', 14),
('puławski', 14),
('radzyński', 14),
('Biała Podlaska', 14),
('Nowy Sącz', 9),
('Gorzów Wielkopolski', 15),
('pilski', 2),
('wysokomazowiecki', 6),
('buski', 4),
('śremski', 2),
('kępiński', 2),
('turecki', 2),
('opatowski', 4),
('Słupsk', 10),
('pińczowski', 4),
('koszaliński', 3),
('bielski', 0),
('będziński', 0),
('węgorzewski', 11),
('bieruńsko-lędziński', 0),
('policki', 3),
('polkowicki', 7),
('Jastrzębie-Zdrój', 0),
('tatrzański', 9),
('nowotarski', 9),
('lwówecki', 7),
('legionowski', 13),
('olecki', 11),
('tomaszowski', 12),
('zambrowski', 6),
('bytowski', 10),
('płocki', 13),
('pułtuski', 13),
('sochaczewski', 13),
('ciechanowski', 13),
('bialski', 14),
('krasnostawski', 14),
('zamojski', 14),
('tarnowski', 9),
('bełchatowski', 12),
('łaski', 12),
('łęczycki', 12),
('pajęczański', 12),
('radomszczański', 12),
('zduńskowolski', 12),
('nowosolski', 15),
('jarosławski', 8),
('mielecki', 8),
('Warszawa', 13),
('krapkowicki', 1),
('moniecki', 6),
('kielecki', 4),
('wrzesiński', 2),
('gnieźnieński', 2),
('malborski', 10),
('lidzbarski', 11),
('olsztyński', 11),
('sławieński', 3),
('działdowski', 11),
('górowski', 7),
('sztumski', 10),
('kwidzyński', 10),
('Dąbrowa Górnicza', 0),
('Mysłowice', 0),
('myśliborski', 3),
('golubsko-dobrzyński', 5),
('aleksandrowski', 5),
('świecki', 5),
('pleszewski', 2),
('Krosno', 8),
('sejneński', 6),
('sanocki', 8),
('suski', 9),
('zielonogórski', 15),
('wołomiński', 13),
('mikołowski', 0),
('goleniowski', 3),
('Rzeszów', 8),
('łomżyński', 6),
('opolski', 1),
('wałecki', 3),
('drawski', 3),
('chojnicki', 10),
('przeworski', 8),
('otwocki', 13),
('kozienicki', 13),
('janowski', 14),
('limanowski', 9),
('miechowski', 9),
('myślenicki', 9),
('olkuski', 9),
('oświęcimski', 9),
('Piotrków Trybunalski', 12),
('poddębicki', 12),
('wieluński', 12),
('brzozowski', 8),
('kędzierzyńsko-kozielski', 1),
('krotoszyński', 2),
('Białystok', 6),
('wolsztyński', 2),
('sandomierski', 4),
('szczecinecki', 3),
('świdwiński', 3),
('piski', 11),
('Świętochłowice', 0),
('Zabrze', 0),
('Olsztyn', 11),
('braniewski', 11),
('kamieński', 3),
('Częstochowa', 0),
('trzebnicki', 7),
('bydgoski', 5),
('oławski', 7),
('średzki', 7),
('legnicki', 7),
('Bydgoszcz', 5),
('Grudziądz', 5),
('rypiński', 5),
('gorlicki', 9),
('lubański', 7),
('wadowicki', 9),
('ostrołęcki', 13),
('Żory', 0),
('nowodworski', 10),
('jaworski', 7),
('poznański', 2),
('koniński', 2),
('All', 0),
('All', 1),
('All', 2),
('All', 3),
('All', 4),
('All', 5),
('All', 6),
('All', 7),
('All', 8),
('All', 9),
('All', 10),
('All', 11),
('All', 12),
('All', 13),
('All', 14),
('All', 15);

CREATE TABLE cases
(
    id_cases    SERIAL
        CONSTRAINT cases_fisrt_key PRIMARY KEY,
    day         date     NOT NULL,
    id_cntry    SMALLINT NOT NULL,
    id_province INT,
    id_district INT,
    cases       SMALLINT,
    deaths      SMALLINT,
    recovered   SMALLINT,
    CONSTRAINT fk_cntry FOREIGN KEY (id_cntry) REFERENCES country (id_cntry),
    CONSTRAINT fk_province FOREIGN KEY (id_province) REFERENCES province (id_province),
    CONSTRAINT fk_district FOREIGN KEY (id_district) REFERENCES district (id_district)
);

CREATE TABLE events
(
    id_event SERIAL
        CONSTRAINT event_fisrt_key PRIMARY KEY,
    day      date     NOT NULL,
    event    VARCHAR NOT NULL
);

INSERT INTO events (day, event) VALUES
('2019-11-17', '(probably) first case of COVID-19, China');

-- co z testami błędnie wykonanymi? other? total? jak to sie ma do cases
-- CREATE TABLE tests
-- (
--     id_tests    SERIAL
--         CONSTRAINT tests_fisrt_key PRIMARY KEY,
--     day         date     NOT NULL,
--     id_cntry    SMALLINT NOT NULL,
--     id_province INT,
--     id_district INT,
--     positive_tests     SMALLINT,
--     negative_tests     SMALLINT,
--     CONSTRAINT fk_cntry FOREIGN KEY (id_cntry) REFERENCES country (id_cntry),
--     CONSTRAINT fk_province FOREIGN KEY (id_province) REFERENCES province (id_province),
--     CONSTRAINT fk_district FOREIGN KEY (id_district) REFERENCES district (id_district)
-- )

-- hospitalizacje, kwarantanna, nadzór
-- CREATE TABLE ?????
-- (
--     id_?????    SERIAL
--         CONSTRAINT ?????_fisrt_key PRIMARY KEY,
--     day         date     NOT NULL,
--     id_cntry    SMALLINT NOT NULL,
--     id_province INT,
--     id_district INT,
--     hospitalisation SMALLINT,
--     quarantine      SMALLINT,
--     supervision     SMALLINT,
--     CONSTRAINT fk_cntry FOREIGN KEY (id_cntry) REFERENCES country (id_cntry),
--     CONSTRAINT fk_province FOREIGN KEY (id_province) REFERENCES province (id_province),
--     CONSTRAINT fk_district FOREIGN KEY (id_district) REFERENCES district (id_district)
-- )

-- czwarte i kolejne dawki?
-- CREATE TABLE vaccination
-- (
--     id_vaccine    SERIAL
--         CONSTRAINT vaccine_fisrt_key PRIMARY KEY,
--     day         date     NOT NULL,
--     id_cntry    SMALLINT NOT NULL,
--     id_province INT,
--     id_district INT,
--     vaccine_1st_dose SMALLINT,
--     vaccine_2nd_dose SMALLINT,
--     vaccine_3rd_dose SMALLINT,
--     CONSTRAINT fk_cntry FOREIGN KEY (id_cntry) REFERENCES country (id_cntry),
--     CONSTRAINT fk_province FOREIGN KEY (id_province) REFERENCES province (id_province),
--     CONSTRAINT fk_district FOREIGN KEY (id_district) REFERENCES district (id_district)
-- )