@startuml LoveAndMarriage
!include plugins/C4-PlantUML/C4_Component.puml

title Level 2: Container architecture diagram

LAYOUT_WITH_LEGEND()

System_Ext(externalSite, "Website in which have data")

Container(scrapper, "ScrapperApp", "Python application")
Container(webInterface, "FrontApp (Web interface)", "FastApi, Dash")
Container(covid19DbApi, "Covid19DB-Api", "FastApi")


ContainerDb(covid19Db, Covid19DB, Postgres)




Rel(externalSite, scrapper, "HTTP")
Rel(scrapper, covid19DbApi, "JSON-RPC")
Rel(webInterface, covid19DbApi, "JSON-RPC")
Rel(covid19DbApi, covid19Db, "psycopg2")




@enduml