apiVersion: v1
data:
  init-db.sql:
    CREATE USER druid WITH PASSWORD 'FoolishPassword';
    
    CREATE DATABASE druid;
  
    GRANT ALL PRIVILEGES ON DATABASE druid TO druid;


kind: ConfigMap
metadata:
  name: init-postgres-db-config