apiVersion: v1
data:
  init-db.sql: CREATE USER druid WITH PASSWORD 'FoolishPassword'; CREATE DATABASE druid WITH OWNER = druid
kind: ConfigMap
metadata:
  name: init-postgres-db-config

---

# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:14.1-alpine
          imagePullPolicy: Never
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
            - name: init-db-script
              mountPath: /docker-entrypoint-initdb.d

#          envFrom:
#            - configMapRef:
#                name: postgres-config
          env:
            - name: POSTGRES_PASSWORD
              value: testpassword
            - name: PGDATA
              value: /data/pgdata
      volumes:
        - name: init-db-script
          configMap:
            name: init-postgres-db-config
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi